title: Biswaranjan Manna
email: manna.biswaranjan@gmail.com
description: Biswaranjan Manna - Student, Library and Information Science
# baseurl:
url: brmanna.github.io
# twitter_username: twitter_username
# github_username:  github_username
# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"
redirects: yes

collections:
  portfolio:
    output: true
    permalink: /projects/:path/

theme: jekyll-theme-minimal
